### ISSUE TITLE
ag-Grid - row details

### ISSUE THREAD

**Issue by samdzirasa** [ceolter/ag-grid-webcomponent#1]
Does the grid support row -details(as in master/child)?  eg - Customers on rows and list of orders (grid format) when clicked?

**Comment by seanlandsman** [comment]
Hi,

You can achieve this via the api and gridOptions, but not via declarative markup

We're working on polymer support at the moment, which will probably offer a richer alternative to "pure" webcomponents if you're interested

thanks
